### ISSUE TITLE
New update PopUp dialogue not showing!

### ISSUE THREAD

**Issue by GitGud31** [larryaasen/upgrader#182]
I'm having some trouble trying to show a pop up dialogue when a new version is available.

 As you can notice from the logs there are some exceptions happening *PlayStoreResults.version*, *PlayStoreResults.releaseNotes* and *PlayStoreResults.description* and I'm not sure why. 

***Some Context*** This version 1.3.4 is already uploaded to the playstore internal testing environment yet the internal testers (with the version v1.3.3) don't receive any popup about the newer version.

***Flutter Code***
```
...
UpgradeAlert(
        upgrader: Upgrader(
          debugLogging: true,
        ),
        child: const HomeScreen(),
      ),
```

Logs
```
I/flutter ( 7859): upgrader: instantiated.
I/flutter ( 7859): upgrader: build UpgradeAlert
I/flutter ( 7859): upgrader: languageCode: en
I/flutter ( 7859): upgrader: default operatingSystem: android QP1A.190711.020.J600FXXSACVB1
I/flutter ( 7859): upgrader: operatingSystem: android
I/flutter ( 7859): upgrader: platform: TargetPlatform.android
I/flutter ( 7859): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 7859): upgrader: package info packageName: com.wilayat.app
I/flutter ( 7859): upgrader: package info appName: wilayat
I/flutter ( 7859): upgrader: package info version: 1.3.4
I/flutter ( 7859): upgrader: countryCode: US
I/flutter ( 7859): upgrader: PlayStoreResults.version exception: Bad state: No element
I/flutter ( 7859): upgrader: PlayStoreResults.releaseNotes exception: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 7859): upgrader: PlayStoreResults.description exception: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 7859): upgrader: blocked: false
I/flutter ( 7859): upgrader: debugDisplayAlways: false
I/flutter ( 7859): upgrader: debugDisplayOnce: false
I/flutter ( 7859): upgrader: hasAlerted: false
I/flutter ( 7859): upgrader: appStoreVersion: null
I/flutter ( 7859): upgrader: installedVersion: 1.3.4
I/flutter ( 7859): upgrader: minAppVersion: null
I/flutter ( 7859): upgrader: isUpdateAvailable: false
I/flutter ( 7859): upgrader: shouldDisplayUpgrade: false
I/flutter ( 7859): upgrader: shouldDisplayReleaseNotes: false
```

The pubspec.lock file:
```
  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
```

**Comment by larryaasen** [comment]
The issue with the Play Store version is documented here: https://github.com/larryaasen/upgrader/issues/179

**Comment by larryaasen** [comment]
I just published version [4.2.1-alpha.1](https://pub.dev/packages/upgrader/versions/4.2.1-alpha.1) on pub.dev with a fix for this thanks to @humanolaranja. Please test out this pre-release version ASAP and provide feedback. After it has been determined that this solution works well, I will release a normal version.

**Comment by GitGud31** [comment]
Hi @larryaasen,

I will push an update to the PlayStore and share the results. This is what I'm getting in the logs after updating to 4.2.1-alpha.1

```
I/flutter ( 2640): upgrader: instantiated.
I/flutter ( 2640): upgrader: build UpgradeAlert
I/flutter ( 2640): upgrader: languageCode: en
I/flutter ( 2640): upgrader: default operatingSystem: android QP1A.190711.020.J600FXXSACVB1
I/flutter ( 2640): upgrader: operatingSystem: android
I/flutter ( 2640): upgrader: platform: TargetPlatform.android
I/flutter ( 2640): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter ( 2640): upgrader: package info packageName: com.wilayat.app
I/flutter ( 2640): upgrader: package info appName: wilayat
I/flutter ( 2640): upgrader: package info version: 1.3.5
I/flutter ( 2640): upgrader: countryCode: US
I/flutter ( 2640): upgrader: PlayStoreResults.version exception, trying redesignedVersion: Bad state: No element
I/flutter ( 2640): upgrader: PlayStoreResults.releaseNotes exception, trying redesignedVersion: RangeError (length): Invalid value: Valid value range is empty: 0
I/flutter ( 2640): upgrader: PlayStoreResults.description exception, trying redesignedVersion: RangeError (length): Invalid value: Valid value range is empty: 0
I/flutter ( 2640): upgrader: PlayStoreResults.minAppVersion: 1.2.3
I/flutter ( 2640): upgrader: blocked: false
I/flutter ( 2640): upgrader: debugDisplayAlways: false
I/flutter ( 2640): upgrader: debugDisplayOnce: false
I/flutter ( 2640): upgrader: hasAlerted: false
I/flutter ( 2640): upgrader: appStoreVersion: 1.3.3
I/flutter ( 2640): upgrader: installedVersion: 1.3.5
I/flutter ( 2640): upgrader: minAppVersion: 1.2.3
I/flutter ( 2640): upgrader: isUpdateAvailable: false
I/flutter ( 2640): upgrader: shouldDisplayUpgrade: false
I/flutter ( 2640): upgrader: shouldDisplayReleaseNotes: true
```
Still get the previous Exception errors, and this is what I get in app (running flutter run --release): 

![Screenshot_20220609-135426](https://user-images.githubusercontent.com/26169532/172870939-90c88d70-ef1c-4658-8035-27f5dd1e49a7.jpg)

**Comment by srihari9n** [comment]
@larryaasen  I am getting these errors on 4.2.1-aplha.1  

I/flutter ( 6585): upgrader: instantiated.
I/flutter ( 6585): upgrader: PlayStoreResults.version exception, trying redesignedVersion: Bad state: No element
I/flutter ( 6585): upgrader: PlayStoreResults.releaseNotes exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 6585): upgrader: PlayStoreResults.description exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0


and I am not getting the popup when the version is old. any guesses on how to fix this?


` UpgradeAlert(
                upgrader: Upgrader(
                  canDismissDialog: false,
                  showIgnore: false,
                  minAppVersion: model.userModel.appLatestVersionNumber,
                  messages: MyUpgraderMessages(),
                  showLater: false,
                  showReleaseNotes: false,
                  countryCode: 'in',
                  dialogStyle: Platform.isAndroid
                      ? UpgradeDialogStyle.material
                      : UpgradeDialogStyle.cupertino,
                ),
                child: FirstLandingScreen(),
              ),`


this is how i setup Upgrade Alert.

**Comment by larryaasen** [comment]
@srihari9n Can you include the entire upgrader log?

**Comment by srihari9n** [comment]
I/flutter ( 5079): upgrader: instantiated.
I/flutter ( 5079): upgrader: PlayStoreResults.version exception, trying redesignedVersion: Bad state: No element
I/flutter ( 5079): upgrader: PlayStoreResults.releaseNotes exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 5079): upgrader: PlayStoreResults.description exception, trying redesignedVersion: RangeError (index): Invalid value: Valid value range is empty: 0

This is all that is getting printed @larryaasen

**Comment by larryaasen** [comment]
I just published version [4.2.1-alpha.2](https://pub.dev/packages/upgrader/versions/4.2.1-alpha.2) to allow for more testing, and removed the noisy exception messages from the log. Please test this new version.

**Comment by srihari9n** [comment]
Okay @larryaasen I checked 4.2.1-alpha.2 and it works perfectly now. Thanks. Did you change any functional things in this version? Just curious, Since I literally changed  just the version in yaml and nothing else.

**Comment by larryaasen** [comment]
> Okay @larryaasen I checked 4.2.1-alpha.2 and it works perfectly now. Thanks. Did you change any functional things in this version? Just curious, Since I literally changed just the version in yaml and nothing else.
> 
> Also, can you please provide some way to suppress the logs that are still there. For eg: `I/flutter ( 5079): upgrader: instantiated.` ?

I did not change the functionality in the 4.2.1-alpha.2 version, but just removed the noisy exception logs. The `upgrader: instantiated.` is going to remain for a little while longer due to the new architecture released in 4.0.0 that may be still confusing to some developers. It should be removed soon.

**Comment by srihari9n** [comment]
@larryaasen  can you consider adding a flag to suppress and un-suppress the logs for future. I don't mind the logs now and I understand the reason. It's just that in future if something goes off, I can turn on the logs to get a better point of view. Just a suggestion of course, you can ignore my suggestion.

**Comment by larryaasen** [comment]
@srihari9n I can do that. Just curious and for the benefit of other developers, what is the impact of having that log statement?

**Comment by srihari9n** [comment]
@larryaasen  call it a trust issue using a few pub.dev packages where the dev created the package in such a way that it would catch the errors and exceptions but don't log anything, so it would silently stop working. So if there is an option to log or not log and it is off by default it would help in those cases.

**Comment by GitGud31** [comment]
@larryaasen, I upgraded to 4.2.1-alpha.2 and it worked for me too

**Comment by larryaasen** [comment]
Version [4.2.1](https://pub.dev/packages/upgrader) has been released to this fix this issue.
