### ISSUE TITLE
Upgrader - version supporting package

### ISSUE THREAD

**Issue by michael-woolsey** [larryaasen/upgrader#189]
Good afternoon,

I just noticed that I cannot upgrade my 3rd party package version to `version: ^3.0.2` as it it locked to an older version in the upgrader package.

`Because xyz depends on upgrader 4.2.2 which depends on version ^2.0.0, version ^2.0.0 is required.`

Hopefully this is something that can be updated as it would be nice to update my other packages.

Thank you,
Michael

**Comment by michael-woolsey** [comment]
It also looks like `device_info_plus: ^4.0.0` is also being blocked by this version of Upgrader.

`Because xyz depends on upgrader 4.2.2 which depends on device_info_plus ^3.2.1, device_info_plus ^3.2.1 is required.`

**Comment by larryaasen** [comment]
@michael-woolsey  I just published an update to this package, [version 4.3.0](https://pub.dev/packages/upgrader/changelog#430), with a fix for this to support `device_info_plus <4.1.0`. Please try it out.

**Comment by larryaasen** [comment]
I still need to resolve the package `version` issue.

**Comment by larryaasen** [comment]
@michael-woolsey I just published an update to this package, [version 4.4.0](https://pub.dev/packages/upgrader/changelog#440), with a fix for this to support version <3.1.0. Please try it out.

**Comment by michael-woolsey** [comment]
Good morning @larryaasen, sorry for the delayed response.  These changes allow my other 3rd party packages to be updated, thank you!

**Comment by rmahmadkhan** [comment]
@larryaasen this issue is still coming on upgrader 5.0.0. Would appreciate an earliest response!

```
Because upgrader >=5.0.0-alpha.1 depends on version ^3.0.2 and my_app depends on version ^2.0.0, upgrader >=5.0.0-alpha.1 is forbidden.
So, because my_app depends on upgrader ^5.0.0, version solving failed.
```
