### ISSUE TITLE
Unhandled Exception: Invalid argument(s) (replacement): Must not be null

### ISSUE THREAD

**Issue by mdags** [larryaasen/upgrader#60]
I'm getting this error in debug.

flutter version 1.20.4 channel stable
upgrader version 2.5.0
xml version 4.2.0

--on ios--
flutter: upgrader: build UpgradeAlert
flutter: upgrader: package info packageName: com.kolayyakit.KolayYakit
flutter: upgrader: package info version: 2.6
flutter: upgrader: countryCode: US
flutter: upgrader: build UpgradeAlert
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s) (replacement): Must not be null
#0      _StringBase.replaceAll (dart:core-patch/string_patch.dart:637:30)
#1      Upgrader.message (package:upgrader/src/upgrader.dart:248:15)
#2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:264:24)
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:325:39)
#4      _rootRun (dart:async/zone.dart:1182:47)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:<…>

--on android--
I/flutter (13693): upgrader: build UpgradeAlert
I/flutter (13693): upgrader: build UpgradeAlert
I/flutter (13693): upgrader: package info packageName: com.ilerleyen.kolayyakit
I/flutter (13693): upgrader: package info version: 2.6.1
I/flutter (13693): upgrader: appcast is available for this platform
E/flutter (13693): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'replaceAll' was called on null.
E/flutter (13693): Receiver: null
E/flutter (13693): Tried calling: replaceAll("{{appName}}", "Kolay Yakıt")
E/flutter (13693): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (13693): #1      Upgrader.message (package:upgrader/src/upgrader.dart:248:15)
E/flutter (13693): #2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:264:24)
E/flutter (13693): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:325:39)
E/flutter (13693): #4      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (13693): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13693): #6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13693): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13693): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13693): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13693): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (13693): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (13693): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (13693): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (13693): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13693): 
I/flutter (13693): "<" expected at 1:1
I/flutter (13693): upgrader: appcast item count: 0

**Comment by mdags** [comment]
When I changed 2.6.0 version problem was solved.

**Comment by larryaasen** [comment]
Should I close this since it was fixed in 2.6.0?

**Comment by 8108905** [comment]
When I changed 2.6.0 version still has problem; i don't know why !  I already changed any version ! but does not fix!
